<a href="https://colab.research.google.com/github/Dayn9/LearnTensorFlow/blob/master/CustomLayers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

tf.enable_eager_execution()

In [0]:
# param_1: number of output dimensions
# param_2: number of input dimensions
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [4]:
layer(tf.zeros([10, 5]))

<tf.Tensor: id=32, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [5]:
layer.variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.49147177,  0.5880129 ,  0.34655958,  0.32511497, -0.15389541,
         -0.350494  , -0.5219081 ,  0.41951996, -0.5459813 ,  0.06236625],
        [-0.53577286,  0.21483958, -0.5961672 , -0.57579184, -0.379362  ,
          0.38032025, -0.29565197,  0.15473968, -0.3487643 ,  0.20016086],
        [ 0.33992022, -0.34530082,  0.57216233,  0.5874979 , -0.25944403,
          0.1017139 ,  0.36146647, -0.18644959, -0.36663747, -0.0061397 ],
        [-0.01196378,  0.5250301 ,  0.20066595, -0.5350768 , -0.40150523,
          0.25918347, -0.2039544 ,  0.06138206, -0.4882117 , -0.42291635],
        [-0.20290506, -0.42357728,  0.49139518, -0.38010794, -0.29247004,
          0.09078324, -0.34122017,  0.4246946 , -0.06069356, -0.1446208 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [6]:
layer.kernel, layer.bias

(<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.49147177,  0.5880129 ,  0.34655958,  0.32511497, -0.15389541,
         -0.350494  , -0.5219081 ,  0.41951996, -0.5459813 ,  0.06236625],
        [-0.53577286,  0.21483958, -0.5961672 , -0.57579184, -0.379362  ,
          0.38032025, -0.29565197,  0.15473968, -0.3487643 ,  0.20016086],
        [ 0.33992022, -0.34530082,  0.57216233,  0.5874979 , -0.25944403,
          0.1017139 ,  0.36146647, -0.18644959, -0.36663747, -0.0061397 ],
        [-0.01196378,  0.5250301 ,  0.20066595, -0.5350768 , -0.40150523,
          0.25918347, -0.2039544 ,  0.06138206, -0.4882117 , -0.42291635],
        [-0.20290506, -0.42357728,  0.49139518, -0.38010794, -0.29247004,
          0.09078324, -0.34122017,  0.4246946 , -0.06069356, -0.1446208 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

## Custom Layers

In [7]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs
    
  def build(self, input_shape):
    self.kernel = self.add_variable("kernel", shape = [int(input_shape[-1]), self.num_outputs])
    
  def call(self, input):
    return tf.matmul(input, self.kernel)
  
  
layer = MyDenseLayer(10)
print(layer(tf.zeros([10, 5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.338732  , -0.4648564 ,  0.16124123, -0.40921158, -0.11538976,
        -0.6114996 , -0.2777559 ,  0.13125998,  0.14014316, -0.6219175 ],
       [ 0.28279674,  0.09606445,  0.01802731, -0.1938129 ,  0.26058322,
        -0.3249506 ,  0.41723496, -0.44317442,  0.44356257,  0.60356766],
       [-0.18025577, -0.4502401 , -0.34328264, -0.08563226,  0.3291216 ,
        -0.43460375,  0.35783893,  0.31821138,  0.12052906, -0.49804586],
       [-0.23089755,  0.43926448, -0.58806485,  0.40988892, -0.38268206,
         0.47965676, -0.26533687, -0

In [0]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name = '')
    filters1, filters2, filters3 = filters
    
    self.conv2a = tf.keras.layers.Conv2D(filters1, (1,1))
    self.bn2a = tf.keras.layers.BatchNormalization()
    
    self.conv2b = tf.keras.layers.Conv2D(filters2, (1,1))
    self.bn2b = tf.keras.layers.BatchNormalization()
    
    self.conv2c = tf.keras.layers.Conv2D(filters3, (1,1))
    self.bn2c = tf.keras.layers.BatchNormalization()
    
  def call(self, input_tensor, training = False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training = training)
    x = tf.nn.relu(x)
    
    x = self.conv2b(x)
    x = self.bn2a(x, training = training)
    x = tf.nn.relu(x)
    
    x = self.conv2b(x)
    x = self.bn2a(x, training = training)
    x += input_tensor
    
    return tf.nn.relu(x)

In [13]:
block = ResnetIdentityBlock(1, [1,2,3])
#print(block(tf.zeros([1, 2, 3, 3])))
print([x.name for x in block.trainable_variables])

[]
