<a href="https://colab.research.google.com/github/Dayn9/LearnTensorFlow/blob/master/Eager.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np
import time

tf.enable_eager_execution()


**Tensor**

multi-dimentional array with a *data type* and *shape*

In [9]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.encode_base64("hello world"))

# Operator overloading is also supported
print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


**Compatible with NumPy**


In [6]:
ndarray = np.ones([3, 3]) #[[1,1,1], [1,1,1], [1,1,1]]
tensor = (tf.multiply(ndarray, 42))
print(tensor)
print(np.add(tensor, 1))
print(tensor.numpy())

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


**Device** fully qualified string name of the device hosing the tensor


the string should end with GPU:[N]


In [11]:
x = tf.random_uniform([3,3])

print(x)
print(tf.test.is_gpu_available()) #check if there is GPU available
print(x.device.endswith('GPU:0')) #check if the tensor is on GPU 0


tf.Tensor(
[[0.21759832 0.82162213 0.5759208 ]
 [0.8320174  0.6652118  0.20224798]
 [0.2834586  0.61974907 0.17528403]], shape=(3, 3), dtype=float32)
False
False


**Dataset**

represents an iput pipeline as a collection of inputs


In [0]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

import tempfile

_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
              Line 2
                Line 3
                """)
  
ds_file = tf.data.TextLineDataset(filename)

In [21]:
# map tensors to square values
#shuffle the order
#batch in sets of 2

ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

for x in ds_tensors: 
  print(x)

for y in ds_file: 
  print(y)

tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([16  9], shape=(2,), dtype=int32)
tf.Tensor([25 36], shape=(2,), dtype=int32)
tf.Tensor([b'Line 1' b'              Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'                Line 3' b'                '], shape=(2,), dtype=string)
